# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.author.name }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#title: Unity6CoreFramework # site.github Sets site.title as the repository name, if none is set
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
# site.github Sets site.description as the repository tagline if none is set
#description: >
#  Framework that contains useful Modules to be Used in Unity Project.

#url: "https://jameslafritz.github.io" # site.github Sets site.url as the GitHub Pages domain (cname or user domain), if none is set
# baseurl: "/Unity6CoreFramework" # site.github 
#domain: jameslafritz.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
#github_username:  JamesLaFritz

author:
  name: James LaFritz
  email: your-email@domain.com

# Build settings

#remote_theme: jekyll/minima - Like the layout includes posts, and uses the new layout of base. base, home, page, posts
#                              Includes: custom-head, disqus_comments, footer, google-analytics, head, social, social-item, svg_symbol
#                              Several custimizable options along with skins.
#remote_theme: pages-themes/modernist@v0.2.0 - Like the look and feel. Only has a default layout
#                                              Includes: head-custom, head-custom-google-analytics
#remote_theme: pages-themes/midnight@v0.2.0 - Like the look and feel. Only has a default layout
#                                              Includes: head-custom, head-custom-google-analytics, head-custom-theme-colors
#remote_theme: pages-themes/hacker@v0.2.0 - Like the colors of this theme. Layout: default, post (dose not auto display posts)
#                                              Includes: head-custom, head-custom-google-analytics, head-custom-theme-colors
#Just the docs - uses GitHub Pages / Actions workflow to build and publish the site on GitHub Pages, Like the side bar and search option.
#                Useful for createing the Manul page of website. Has a bunch of includes. To set up see https://github.com/JamesLaFritz/Use-Just-The-Docs_Theme
#                Layouts: about, default, home, minimal, page, post, table wrappers.
# https://github.com/CloudCannon/aviator-jekyll-template Almost set up for use as the way i want.
# https://github.com/sujaykundu777/devlopr-jekyll great for user io page.
# remote_theme: daviddarnes/alembic@main a good one to look at in setting up additional settings for a site.

remote_theme: pages-themes/hacker@v0.2.0

plugins:
  # Git-Hub enabled by default.
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  # additional avaliable on git hub
  - jekyll-remote-theme

show_downloads: true

# Some configuration settings cannot be changed for GitHub Pages sites. 
lsi: false
safe: true
source: https://github.com/JamesLaFritz/Unity6CoreFramework #[your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
