# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
# bundle exec jekyll serve --livereload

# Some configuration settings cannot be changed for GitHub Pages sites. 
lsi: false
safe: true
#source: . #[your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.author.name }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Unity CoreFramework # site.github Sets site.title as the repository name, if none is set

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
# site.github Sets site.description as the repository tagline if none is set
description: >
  Framework that contains useful Modules to be Used in Unity Project.

url: "https://jameslafritz.github.io/Unity6CoreFramework/" # site.github Sets site.url as the GitHub Pages domain (cname or user domain), if none is set
baseurl: "/Unity6CoreFramework"       # Sets site.baseurl as the project name for project pages if none is set
domain: jameslafritz.github.io        # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
github_username:  JamesLaFritz

author:
  name: James LaFritz
  email: your-email@domain.com

show_downloads: true
  
permalink: pretty
#show_excerpts: true
#google_analytics: #[Your Google Analytics tracking ID]

#github:
  #zip_url: http://example.com/download.zip
  #another_url: another value

# Build settings

#remote_theme: jekyll/minima - Like the layout includes posts, and uses the new layout of base. base, home, page, posts
#                              Includes: custom-head, disqus_comments, footer, google-analytics, head, social, social-item, svg_symbol
#                              Several custimizable options along with skins.
#remote_theme: pages-themes/modernist@v0.2.0 - Like the look and feel. Only has a default layout
#                                              Includes: head-custom, head-custom-google-analytics
#remote_theme: pages-themes/midnight@v0.2.0 - Like the look and feel. Only has a default layout
#                                              Includes: head-custom, head-custom-google-analytics, head-custom-theme-colors
#remote_theme: pages-themes/hacker@v0.2.0 - Like the colors of this theme. Layout: default, post (dose not auto display posts)
#                                              Includes: head-custom, head-custom-google-analytics, head-custom-theme-colors
#Just the docs - uses GitHub Pages / Actions workflow to build and publish the site on GitHub Pages, Like the side bar and search option.
#                Useful for createing the Manul page of website. Has a bunch of includes. To set up see https://github.com/JamesLaFritz/Use-Just-The-Docs_Theme
#                Layouts: about, default, home, minimal, page, post, table wrappers.
# https://github.com/CloudCannon/aviator-jekyll-template Almost set up for use as the way I want.
# https://github.com/sujaykundu777/devlopr-jekyll great for user io page.
# remote_theme: daviddarnes/alembic@main a good one to look at in setting up additional settings for a site.

remote_theme: jekyll/minima

plugins:
  # Git-Hub enabled by default.
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  # additional avaliable on git hub
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
    
excludes:
  - .idea
  - .gitignore
  - gitattributes

collections_dir: ./collections

collections:
  - man-pages
  - api-pages

defaults:
  -
    scope:
      path: "api"
      type: "pages"
    values:
      layout: "api-page"
  -
    scope:
      path: "manual"
      type: "pages"
    values:
      layout: "man-page"
      

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md
  - manual/coreframework-man-home.md
  - api/api-home.md

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: auto
  
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  # Generate social links in footer.
  #social_links:
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #  - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #  - { platform: gitlab,         user_url: "https://gitlab.com/jekyll" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }