name: activate_Unity
on: workflow_dispatch
jobs:
  activate:
    name: activate
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
            
