name: activate_Unity
on: workflow_dispatch
jobs:
  activate_license:
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Request Activation File
        uses: game-ci/unity-request-activation-file@v2.2.0
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      - name: Unity - Builder
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
      - name: Unity - Return License
        uses: game-ci/unity-return-license@v2.0.0    
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - WebGL # WebGL.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - LinuxHeadlessSimulation	# Build a LinuxHeadlessSimulation standalone.
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          - WSAPlayer # Build an Windows Store Apps player.
          - tvOS	# Build to Apple's tvOS platform.
          - VisionOS	# Build a visionOS player.
          - PS4	# Build a PS4 Standalone.
          - PS5	# Build to PlayStation 5 platform.
          - XboxOne	# Build a Xbox One Standalone.
          - Switch	# Build a Nintendo Switch player.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
      - uses: game-ci/unity-builder@v4
        id: myBuildStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}-${{ steps.myBuildStep.outputs.buildVersion }}
          path: build/${{ matrix.targetPlatform }}-${{ steps.myBuildStep.outputs.buildVersion }}
            
